### ISSUE TITLE
 System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by byehack** [ynkdir/winmd-printer#1]
trying on build win32metada version 49:
winmd-printer> dotnet run Windows.Win32.winmd > Windows.Win32.json
```
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at TypeProvider.GetUnderlyingEnumType(TType type) in C:\Users\Desktop\winmd-printer\Program.cs:line 241
   at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeFixedArgumentType(BlobReader& signatureReader, BlobReader genericContextReader, Boolean isElementType)
   at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeFixedArguments(BlobReader& signatureReader, BlobReader& valueReader, Int32 count, BlobReader genericContextReader)
   at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeValue(EntityHandle constructor, BlobHandle value)
   at System.Reflection.Metadata.CustomAttribute.DecodeValue[TType](ICustomAttributeTypeProvider`1 provider)
   at JsCustomAttribute..ctor(MetadataReader reader, CustomAttribute ca) in C:\Users\Desktop\winmd-printer\Program.cs:line 385
   at JsMethodDefinition.<get_CustomAttributes>b__9_0(CustomAttributeHandle h) in C:\Users\Desktop\winmd-printer\Program.cs:line 580
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at MetadataPrinter.Main(String[] args) in C:\Users\Desktop\winmd-printer\Program.cs:line 700
```

**Comment by byehack** [comment]
fixed by adding
```cs
            "Windows.Win32.Foundation.Metadata.Architecture" => PrimitiveTypeCode.Int32,

```
to line 241. at least temporarily worked for me until ynkdir fixes it.

**Comment by ynkdir** [comment]
Thank you.
